Repository DeveloperAcademy-POSTECH/2024-MacC-A2-PohangEgrets, pull requests merged in 2024-11, with the labels that each got.

#41 [#35] 방 참가 시 방에 대한 정보 표출 및 호스트 표출
  AsyncC.xcodeproj/xcshareddata/xcschemes/AsyncC.xcscheme
  AsyncC/Resource/Assets.xcassets/Color/Contents.json
  AsyncC/Resource/Assets.xcassets/Color/HostBackground.colorset/Contents.json
  AsyncC/Resource/Assets.xcassets/Color/HostStroke.colorset/Contents.json
  AsyncC/Resource/Assets.xcassets/Color/HostText.colorset/Contents.json
  AsyncC/Resource/Assets.xcassets/Color/PannelBackground.colorset/Contents.json
  AsyncC/Resource/Assets.xcassets/Color/TeamCodeText.colorset/Contents.json
  AsyncC/Source/Presentation/MainStatusView/Components/HostView.swift
  AsyncC/Source/Presentation/MainStatusView/Components/TeamCodeView.swift
  AsyncC/Source/Presentation/MainStatusView/MainStatusView.swift
  AsyncC/Source/Presentation/MainStatusView/MainStatusViewModel.swift
Labels: enhancement

#51 [#48] MainStatus 구현
  AsyncC/Resource/Assets.xcassets/Color/Gray1.colorset/Contents.json
  AsyncC/Resource/Assets.xcassets/Color/LightBlue.colorset/Contents.json
  AsyncC/Resource/Assets.xcassets/Image/Contents.json
  AsyncC/Resource/Assets.xcassets/Image/CreateTeamIcon.imageset/Contents.json
  AsyncC/Resource/Assets.xcassets/Image/CreateTeamIcon.imageset/CreateTeamIcon 1.png
  AsyncC/Resource/Assets.xcassets/Image/CreateTeamIcon.imageset/CreateTeamIcon 2.png
  AsyncC/Resource/Assets.xcassets/Image/CreateTeamIcon.imageset/CreateTeamIcon.png
  AsyncC/Resource/Assets.xcassets/Image/Discord.imageset/Contents.json
  AsyncC/Resource/Assets.xcassets/Image/Discord.imageset/discord 1.png
  AsyncC/Resource/Assets.xcassets/Image/Discord.imageset/discord 2.png
  AsyncC/Resource/Assets.xcassets/Image/Discord.imageset/discord 3.png
  AsyncC/Resource/Assets.xcassets/Image/Google Chrome.imageset/Contents.json
  AsyncC/Resource/Assets.xcassets/Image/Google Chrome.imageset/google-chrome 1.png
  AsyncC/Resource/Assets.xcassets/Image/Google Chrome.imageset/google-chrome 2.png
  AsyncC/Resource/Assets.xcassets/Image/Google Chrome.imageset/google-chrome.png
  AsyncC/Resource/Assets.xcassets/Image/JoinTeamIcon.imageset/Contents.json
  AsyncC/Resource/Assets.xcassets/Image/JoinTeamIcon.imageset/JoinTeam 1.png
  AsyncC/Resource/Assets.xcassets/Image/JoinTeamIcon.imageset/JoinTeam 2.png
  AsyncC/Resource/Assets.xcassets/Image/JoinTeamIcon.imageset/JoinTeam.png
  AsyncC/Resource/Assets.xcassets/Image/Microsoft Teams.imageset/Contents.json
  AsyncC/Resource/Assets.xcassets/Image/Microsoft Teams.imageset/teams 1.png
  AsyncC/Resource/Assets.xcassets/Image/Microsoft Teams.imageset/teams 2.png
  AsyncC/Resource/Assets.xcassets/Image/Microsoft Teams.imageset/teams 3.png
  AsyncC/Resource/Assets.xcassets/Image/figma.imageset/Contents.json
  AsyncC/Resource/Assets.xcassets/Image/figma.imageset/figma 1.png
  AsyncC/Resource/Assets.xcassets/Image/figma.imageset/figma 2.png
  AsyncC/Resource/Assets.xcassets/Image/figma.imageset/figma.png
  AsyncC/Resource/Assets.xcassets/Image/finder.imageset/Contents.json
  AsyncC/Resource/Assets.xcassets/Image/finder.imageset/finder 1.png
  AsyncC/Resource/Assets.xcassets/Image/finder.imageset/finder 2.png
  AsyncC/Resource/Assets.xcassets/Image/finder.imageset/finder.png
  AsyncC/Resource/Assets.xcassets/Image/iphone 미러링.imageset/Contents.json
  AsyncC/Resource/Assets.xcassets/Image/iphone 미러링.imageset/mirroring 1.png
  AsyncC/Resource/Assets.xcassets/Image/iphone 미러링.imageset/mirroring 2.png
  AsyncC/Resource/Assets.xcassets/Image/iphone 미러링.imageset/mirroring 3.png
  AsyncC/Resource/Assets.xcassets/Image/xcode.imageset/Contents.json
  AsyncC/Resource/Assets.xcassets/Image/xcode.imageset/xcode 1.png
  AsyncC/Resource/Assets.xcassets/Image/xcode.imageset/xcode 2.png
  AsyncC/Resource/Assets.xcassets/Image/xcode.imageset/xcode.png
  AsyncC/Resource/Assets.xcassets/Image/구름영감.imageset/Contents.json
  AsyncC/Resource/Assets.xcassets/Image/구름영감.imageset/cloudsage 1.png
  AsyncC/Resource/Assets.xcassets/Image/구름영감.imageset/cloudsage 2.png
  AsyncC/Resource/Assets.xcassets/Image/구름영감.imageset/cloudsage 3.png
  AsyncC/Resource/Assets.xcassets/Image/카카오톡.imageset/Contents.json
  AsyncC/Resource/Assets.xcassets/Image/카카오톡.imageset/kakaotalk 1.png
  AsyncC/Resource/Assets.xcassets/Image/카카오톡.imageset/kakaotalk 2.png
  AsyncC/Resource/Assets.xcassets/Image/카카오톡.imageset/kakaotalk 3.png
  AsyncC/Source/Data/Repositories/FirebaseRepository.swift
  AsyncC/Source/Domain/RepositoryInterfaces/FirebaseRepositoryProtocol.swift
  AsyncC/Source/Domain/UseCases/TeamManagingUseCase.swift
  AsyncC/Source/Presentation/MainStatusView/Components/AppTrackingBoxView.swift
  AsyncC/Source/Presentation/MainStatusView/Components/HostView.swift
  AsyncC/Source/Presentation/MainStatusView/Components/TeamCodeView.swift
  AsyncC/Source/Presentation/MainStatusView/MainStatusView.swift
  AsyncC/Source/Presentation/MainStatusView/MainStatusViewModel.swift
Labels: feat

#53 [#52] - CheckToJoinTeam 구현, 팀이 없으면 에러 메세지 띄우기
  AsyncC/Source/Presentation/CheckToJoinTeam/CheckToJoinTeamView.swift
  AsyncC/Source/Presentation/CheckToJoinTeam/CheckToJoinTeamViewModel.swift
  AsyncC/Source/Presentation/Flow/Router.swift
  AsyncC/Source/Presentation/JoinTeamView/JoinTeamView.swift
  AsyncC/Source/Presentation/JoinTeamView/JoinTeamViewModel.swift
Labels: design

#56 [#54] - MainStatusView 모든delay fix
  AsyncC/Source/Data/Repositories/FirebaseRepository.swift
  AsyncC/Source/Presentation/MainStatusView/MainStatusViewModel.swift
Labels: fix

#62 [#59] 메인 판넬 정렬 수정, 팀 코드 복사 수정, 방 나가기 이후 앱 크래쉬 해결
  AsyncC/Source/Data/Repositories/LocalRepository.swift
  AsyncC/Source/Domain/RepositoryInterfaces/LocalRepositoryProtocol.swift
  AsyncC/Source/Presentation/MainStatusView/Components/AppTrackingBoxView.swift
  AsyncC/Source/Presentation/MainStatusView/Components/TeamCodeView.swift
  AsyncC/Source/Presentation/MainStatusView/MainStatusViewModel.swift
Labels: fix

#78 [#77] MainStatusView 구현 및 컴포넌트화
  AsyncC/Resource/Assets.xcassets/Image/Figma.imageset/Contents.json
  AsyncC/Resource/Assets.xcassets/Image/Figma.imageset/figma 1.png
  AsyncC/Resource/Assets.xcassets/Image/Figma.imageset/figma 2.png
  AsyncC/Resource/Assets.xcassets/Image/Figma.imageset/figma.png
  AsyncC/Resource/Assets.xcassets/Image/Finder.imageset/Contents.json
  AsyncC/Resource/Assets.xcassets/Image/Finder.imageset/finder 1.png
  AsyncC/Resource/Assets.xcassets/Image/Finder.imageset/finder 2.png
  AsyncC/Resource/Assets.xcassets/Image/Finder.imageset/finder.png
  AsyncC/Resource/Assets.xcassets/Image/Xcode.imageset/Contents.json
  AsyncC/Resource/Assets.xcassets/Image/Xcode.imageset/xcode 1.png
  AsyncC/Resource/Assets.xcassets/Image/Xcode.imageset/xcode 2.png
  AsyncC/Resource/Assets.xcassets/Image/Xcode.imageset/xcode.png
  AsyncC/Resource/Assets.xcassets/Image/iPhone 미러링.imageset/Contents.json
  AsyncC/Resource/Assets.xcassets/Image/iPhone 미러링.imageset/mirroring 1.png
  AsyncC/Resource/Assets.xcassets/Image/iPhone 미러링.imageset/mirroring 2.png
  AsyncC/Resource/Assets.xcassets/Image/iPhone 미러링.imageset/mirroring 3.png
  AsyncC/Source/Presentation/MainStatusView/Components/AppIconBoxContentView.swift
  AsyncC/Source/Presentation/MainStatusView/Components/AppIconBoxHeaderView.swift
  AsyncC/Source/Presentation/MainStatusView/Components/AppTrackingBoxView.swift
  AsyncC/Source/Presentation/MainStatusView/Components/HostView.swift
  AsyncC/Source/Presentation/MainStatusView/Components/SyncButton.swift
  AsyncC/Source/Presentation/MainStatusView/MainStatusView.swift
  AsyncC/Source/Presentation/MainStatusView/MainStatusViewModel.swift
Labels: design

#83 [#70] toggle에 따라 TrackingActive true/false 전환 listener로 팀원에게 상태 공유 후 상태 반영
  AsyncC/Resource/Assets.xcassets/Color/ButtonDefault.colorset/Contents.json
  AsyncC/Source/Data/Repositories/FirebaseRepository.swift
  AsyncC/Source/Domain/Entity/TrackingActive.swift
  AsyncC/Source/Domain/RepositoryInterfaces/FirebaseRepositoryProtocol.swift
  AsyncC/Source/Domain/UseCases/AppTrackingUseCase.swift
  AsyncC/Source/Domain/UseCases/TeamManagingUseCase.swift
  AsyncC/Source/Presentation/MainStatusView/Components/AppIconBoxContentView.swift
  AsyncC/Source/Presentation/MainStatusView/Components/AppIconBoxHeaderView.swift
  AsyncC/Source/Presentation/MainStatusView/Components/AppTrackingBoxView.swift
  AsyncC/Source/Presentation/MainStatusView/Components/SyncButton.swift
  AsyncC/Source/Presentation/MainStatusView/MainStatusView.swift
  AsyncC/Source/Presentation/MainStatusView/MainStatusViewModel.swift
Labels: feat

#94 Fix/#88 - sync와 관련된 window가 계속 잘못된 타이밍에 나오는 bug 잡기
  AsyncC/App/AsyncCApp.swift
  AsyncC/Source/Domain/UseCases/SyncUseCase.swift
  AsyncC/Source/Presentation/Flow/Router.swift
Labels: fix

#96 [#95] - JoinTeamView 버튼 밑에 padding이 다른 뷰와 불일치한거 고치기
  AsyncC/Source/Presentation/JoinTeamView/JoinTeamView.swift
Labels: fix

#97 [#57] JoinTeamView에서 팀이 존재하는데 팀이 없다는 에러가 잘못 뜨는상황 고침
  AsyncC/Source/Data/Repositories/FirebaseRepository.swift
Labels: fix

#105 [#99] - sync 요청을 여러번 눌렀을때 request가 여러번 오고 창이 안닫치는 버그 해결
  AsyncC/Source/Data/Repositories/FirebaseRepository.swift
  AsyncC/Source/Domain/RepositoryInterfaces/FirebaseRepositoryProtocol.swift
  AsyncC/Source/Domain/UseCases/SyncUseCase.swift
Labels: fix

#110 [#91] firebaseAuth변경: 로그인, 로그아웃, Auth탈퇴 구현 + GroupActivity Capability 포함
  AsyncC.xcodeproj/project.pbxproj
  AsyncC/AsyncC.entitlements
  AsyncC/Source/Data/Repositories/FirebaseRepository.swift
  AsyncC/Source/Data/Repositories/LocalRepository.swift
  AsyncC/Source/Domain/RepositoryInterfaces/FirebaseRepositoryProtocol.swift
  AsyncC/Source/Domain/RepositoryInterfaces/LocalRepositoryProtocol.swift
  AsyncC/Source/Domain/UseCases/AccountManagingUseCase.swift
  AsyncC/Source/Presentation/CreateOrJoinTeam/CreateOrJoinTeamView.swift
  AsyncC/Source/Presentation/CreateOrJoinTeam/CreateOrJoinTeamViewModel.swift
  AsyncC/Source/Presentation/Flow/Router.swift
  AsyncC/Source/Presentation/Login/LoginView.swift
Labels: refactor

#112 [#111] 회원탈퇴, 로그아웃 기능 버튼에 매핑
  AsyncC/Source/Presentation/Flow/Router.swift
  AsyncC/Source/Presentation/Login/AccountDeleteView.swift
  AsyncC/Source/Presentation/Login/LoginView.swift
  AsyncC/Source/Presentation/Login/LogoutView.swift
Labels: fix

#114 [#113] 회원탈퇴 후 강제 앱 재시작시 Window로 가는 버그 수정
  AsyncC/Source/Domain/UseCases/AccountManagingUseCase.swift
Labels: fix

#116 [#115] 애플 토큰 삭제: 애플 로그인 삭제 구현
  AsyncC/Source/Domain/UseCases/AccountManagingUseCase.swift
  AsyncC/Source/Extension/Extension + Date.swift
  AsyncC/Source/Presentation/Login/AccountDeleteView.swift
Labels: feat

#118 [#117] CreateOrJoinTeamView 이름 안뜨는 버그 수정
  AsyncC/Source/Domain/UseCases/AccountManagingUseCase.swift
  AsyncC/Source/Presentation/CreateOrJoinTeam/CreateOrJoinTeamView.swift
  AsyncC/Source/Presentation/CreateOrJoinTeam/CreateOrJoinTeamViewModel.swift
Labels: fix

#121 [Feat] FaceTime 기능 추가
  AsyncC.xcodeproj/project.pbxproj
  AsyncC/App/AsyncCApp.swift
  AsyncC/AsyncC.entitlements
  AsyncC/Source/Data/Repositories/FirebaseRepository.swift
  AsyncC/Source/Domain/Entity/SyncRequest.swift
  AsyncC/Source/Domain/Entity/UserAppData.swift
  AsyncC/Source/Domain/RepositoryInterfaces/FirebaseRepositoryProtocol.swift
  AsyncC/Source/Domain/UseCases/FaceTimeUseCase.swift
  AsyncC/Source/Domain/UseCases/SyncUseCase.swift
  AsyncC/Source/Domain/UseCases/TeamManagingUseCase.swift
  AsyncC/Source/Extension/Extension + HUDWindow.swift
  AsyncC/Source/Extension/Extension + SyncRequestWindow.swift
  AsyncC/Source/Extension/Extension + SyncingLoadingWindow.swift
  AsyncC/Source/Presentation/Flow/Router.swift
  AsyncC/Source/Presentation/MainStatusView/Components/AppTrackingBoxView.swift
  AsyncC/Source/Presentation/MainStatusView/MainStatusViewModel.swift
  AsyncC/Source/Presentation/NotificationView/PendingSyncRequestView.swift
  AsyncC/Source/Presentation/NotificationView/SyncRequestNotificationViewModel.swift
  AsyncC/Source/Presentation/NotificationView/SyncingView.swift
Labels: feat
